spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka
  instance:
    instance-id:  ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    #    租期更新时间间隔 秒
    lease-renewal-interval-in-seconds: 1
    #    租期到期时间 秒
    lease-expiration-duration-in-seconds: 3
server:
  port: 8080
  # ipv6 不能用ip访问
  address: 0.0.0.0


